server:
  port: 8000

logging:
  level:
    com.ivrs: DEBUG


spring:
  application:
    name: Reference-Data-Application-Service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ivrs_auth  # Default Datasource (required)
    username: postgres
    password: Puretech@18

    falcon:
      jdbc-url: jdbc:postgresql://localhost:5432/ivrs_db
      username: postgres
      password: Puretech@18
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        idle-timeout: 30000
        max-lifetime: 1800000
        connection-timeout: 30000

    pcdao-ivrs:
      jdbc-url: jdbc:postgresql://localhost:5432/ivrs_auth
      username: postgres
      password: Puretech@18
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 5
        minimum-idle: 1
        idle-timeout: 30000
        max-lifetime: 1800000
        connection-timeout: 30000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
    falcon:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
        show-sql: true
        format_sql: true
    pcdao-ivrs:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
        show-sql: true
        format_sql: true

